### ISSUE TITLE
Question - Wwo batteries in series

### ISSUE THREAD

**Issue by Caine85** [nocko/tdcs#1]
Hi, thank you for your work! I know this project is stopped for some years, but it would be possible to know if with  v4 layout of the PCB I can connect two 9V batteries in series to achieve a higher voltage?
Thanks a lot!

**Comment by nocko** [comment]
Hi,
  I don't recommend using these designs. While they work, they are not rigorously tested. 

To answer your question; the trick with the v4 design is that it has a voltage doubler on board (LT1026), it's actually wired as a voltage quadrupler... to 9V in gets you up to 36V at the output (which is more than enough). 

The "absolute maximum" input voltage to the doubler chip is 10V, so putting two 9V in series on the input would almost certainly fry the chip; the current is regulated to 2mA, so putting them in parallel isn't useful either.
